name: CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest, windows-latest]
        dotnet: [ '5.0.x' ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Setup ib
      run: |
        dotnet tool install --global ib
      env:
        CI: true

    - name: Test
      run: ib Test
      env:
        CI: true
